const AZ_TASK_TITLES = {
  'Reliable Prompt Template': 'Etibarlı prompt şablonu',
  'Document Q&A Prototype': 'Sənədlər üzrə sual-cavab prototipi',
  'AI Evaluation Report': 'Süni intellekt qiymətləndirmə hesabatı',
  'Final AI Product Feature': 'Yekun süni intellekt məhsulu funksiyası',
  'Prompt Failure Cases': 'Prompt xətaları və uğursuz nümunələr',
  'Tool Calling Prototype': 'Alət çağırışı prototipi',
  'RAG Quality Tuning': 'RAG keyfiyyətinin təkmilləşdirilməsi',
  'Guardrails': 'Təhlükəsizlik məhdudiyyətləri',
  'Cost and Latency': 'Xərc və cavab gecikməsi',
  'AI Product Handoff': 'Süni intellekt məhsulunun təhvil verilməsi',
  'Process Mapping': 'Prosesin xəritələndirilməsi',
  'Webhook to Workflow': 'Webhook-dan avtomatlaşdırılmış iş axınına',
  'Retries and Monitoring': 'Təkrar cəhdlər və monitorinq',
  'Final Automation Case Study': 'Yekun avtomatlaşdırma layihəsi',
  'Data Transformation': 'Məlumatların çevrilməsi',
  'API Integration': 'API inteqrasiyası',
  'Scheduled Workflow': 'Planlaşdırılmış iş axını',
  'Notification Flow': 'Bildiriş axını',
  'Automation Metrics': 'Avtomatlaşdırma göstəriciləri',
  'Automation Case Handoff': 'Avtomatlaşdırma layihəsinin təhvil verilməsi',
  'REST API Design': 'REST API dizaynı',
  'PostgreSQL Data Model': 'PostgreSQL məlumat modeli',
  'Authentication and Validation': 'Autentifikasiya və yoxlama',
  'Final Backend Service': 'Yekun backend xidməti',
  'Pagination and Filtering': 'Səhifələmə və filtrləmə',
  'Database Transactions': 'Verilənlər bazası tranzaksiyaları',
  'API Documentation': 'API sənədləşdirilməsi',
  'Backend Testing': 'Backend testləri',
  'Logging and Errors': 'Loqlar və xətaların idarə edilməsi',
  'Backend Deployment': 'Backend-in yayımlanması',
  'Security Lab Setup': 'Təhlükəsizlik laboratoriyasının qurulması',
  'HTTP and Headers': 'HTTP və başlıqlar',
  'XSS Awareness': 'XSS zəifliyi barədə məlumatlılıq',
  'SQL Injection Awareness': 'SQL injection zəifliyi barədə məlumatlılıq',
  'Access Control Review': 'Girişə nəzarətin yoxlanılması',
  'JWT Review': 'JWT təhlükəsizliyinin yoxlanılması',
  'API Security Checklist': 'API təhlükəsizliyi yoxlama siyahısı',
  'ZAP Passive Scan': 'ZAP ilə passiv skan',
  'Secure Coding Fixes': 'Təhlükəsiz kodlaşdırma düzəlişləri',
  'Final Security Report': 'Yekun təhlükəsizlik hesabatı',
  'Dataset Cleaning': 'Məlumat dəstinin təmizlənməsi',
  'SQL KPI Analysis': 'SQL ilə KPI təhlili',
  'Insight Dashboard': 'Analitik nəticələr paneli',
  'Final Data Case Study': 'Yekun məlumat təhlili layihəsi',
  'Data Validation': 'Məlumatların yoxlanılması',
  'Exploratory Analysis': 'Kəşfiyyat xarakterli təhlil',
  'Cohort Analysis': 'Kohort təhlili',
  'Dashboard Review': 'İdarəetmə panelinin yoxlanılması',
  'Data Storytelling': 'Məlumatlarla hekayələndirmə',
  'Reproducible Analysis': 'Təkrarlana bilən təhlil',
  'Responsive Landing Page': 'Adaptiv açılış səhifəsi',
  'Reusable Component System': 'Təkrar istifadə edilə bilən komponent sistemi',
  'API-powered Dashboard': 'API ilə işləyən idarəetmə paneli',
  'Final Frontend Project': 'Yekun frontend layihəsi',
  'Accessible Form Flow': 'Əlçatan forma prosesi',
  'State Management': 'Vəziyyətin idarə edilməsi',
  'Performance Pass': 'Performansın optimallaşdırılması',
  'Frontend Testing': 'Frontend testləri',
  'Code Review Fixes': 'Kod yoxlamasından sonra düzəlişlər',
  'Frontend Handoff': 'Frontend layihəsinin təhvil verilməsi',
  'Expo Setup': 'Expo mühitinin qurulması',
  'Navigation Flow': 'Naviqasiya axını',
  'Reusable Mobile Components': 'Təkrar istifadə edilə bilən mobil komponentlər',
  'API Mobile List': 'API-dən məlumat alan mobil siyahı',
  'Search and Filter': 'Axtarış və filtrləmə',
  'Local Storage': 'Lokal yaddaş',
  'Form Validation': 'Formanın yoxlanılması',
  'Offline State': 'Oflayn vəziyyətin idarə edilməsi',
  'Mobile UX Test': 'Mobil istifadəçi təcrübəsi testi',
  'Final Mobile App': 'Yekun mobil tətbiq',
  'User Interview Plan': 'İstifadəçi müsahibəsi planı',
  'User Flow': 'İstifadəçi axını',
  'Low-Fidelity Wireframe': 'Sadə ilkin maket',
  'High-Fidelity Screens': 'Detallı ekran dizaynları',
  'Design System': 'Dizayn sistemi',
  'Prototype Interaction': 'Prototipdə qarşılıqlı əlaqə',
  'Accessibility Review': 'Əlçatanlığın yoxlanılması',
  'Responsive Adaptation': 'Adaptiv dizayn',
  'UX Usability Test': 'UX istifadə rahatlığı testi',
  'Final UX Case Study': 'Yekun UX layihəsi',
};

/**
 * Return a translated task title for Azerbaijani while preserving the canonical
 * English title in English mode and unknown future titles.
 * @param {string|null|undefined} title
 * @param {'az'|'en'} locale
 */
export function getLocalizedTaskTitle(title, locale) {
  if (typeof title !== 'string') return '';
  return locale === 'az' ? (AZ_TASK_TITLES[title] ?? title) : title;
}
